import { Activity, ArrowRight, BarChart3, CalendarCheck, Check, CircleDollarSign, Clock3, Columns3, Download, Factory, FileText, Flame, Layers, Linkedin, Mail, MessageCircle, Phone, Repeat2, Search, ShieldCheck, Star, Sun, Target, Trophy, UserCheck, Users, Video, Workflow, Zap, type LucideIcon } from 'lucide-react';
import type { DeckSlide, Tile } from './onboarding-content';
import carrefour from '@/assets/clientes/Carrefour_logo.png';
import cvale from '@/assets/clientes/C._Vale_logo.png';
import korin from '@/assets/clientes/Korin_logo.png';
const clientLogos: Record<string,string> = {carrefour,cvale,korin};
const icons: Record<string, LucideIcon> = {activity:Activity,arrow:ArrowRight,chart:BarChart3,calendar:CalendarCheck,check:Check,clock:Clock3,columns:Columns3,download:Download,factory:Factory,file:FileText,flame:Flame,layers:Layers,linkedin:Linkedin,mail:Mail,message:MessageCircle,money:CircleDollarSign,phone:Phone,repeat:Repeat2,search:Search,shield:ShieldCheck,star:Star,sun:Sun,target:Target,trophy:Trophy,user:UserCheck,users:Users,video:Video,workflow:Workflow,zap:Zap};
const Icon = ({name,size=34}:{name?:string;size?:number}) => {const Glyph=icons[name??'target']??Target;return <Glyph size={size} strokeWidth={1.7}/>;};
function Lines({text}:{text:string}) {return <>{text.split('\n').map((line,i)=><span className="block" key={i}>{line}</span>)}</>;}
function TileBody({tile,index,dark=false}:{tile:Tile;index:number;dark?:boolean}) {return <><div className="flex items-center justify-between"><span className={`grid size-16 place-items-center rounded-lg ${dark?'bg-accent/20 text-accent-glow':'bg-accent/10 text-accent'}`}><Icon name={tile.icon}/></span><span className={`text-[38px] font-bold ${dark?'text-primary-foreground/20':'text-muted-foreground/30'}`}>{String(index+1).padStart(2,'0')}</span></div>{tile.tag&&<div className={`mt-7 text-[15px] font-bold ${dark?'text-accent-glow':'text-accent'}`}>{tile.tag}</div>}<h3 className={`mt-5 text-[27px] font-bold leading-[1.25] ${dark?'text-primary-foreground':'text-foreground'}`}>{tile.title}</h3><p className={`mt-5 text-[21px] leading-[1.55] ${dark?'text-primary-foreground/75':'text-muted-foreground'}`}><Lines text={tile.text}/></p></>;}
export default function OnboardingVisual({slide}:{slide:DeckSlide}) {
 const tiles=slide.tiles??[];const dark=!!slide.dark;const ink=dark?'text-primary-foreground':'text-foreground';const muted=dark?'text-primary-foreground/70':'text-muted-foreground';
 if(slide.layout==='call-detail') return <div className={`sdr-visual grid gap-8 ${tiles.length===2?'grid-cols-2':'grid-cols-3'}`}>{tiles.map(t=><div key={t.title} className="flex min-w-0 flex-col border-t-4 border-accent pt-5"><div className="flex items-center gap-4 text-accent"><Icon name={t.icon} size={30}/><span className="text-[16px] font-bold">{t.tag}</span></div><h3 className="mt-5 text-[29px] font-bold leading-[1.3]">{t.title}</h3><p className="mt-5 text-[22px] leading-[1.5] text-muted-foreground">{t.text}</p><blockquote className="mt-6 border-l-4 border-accent bg-secondary px-5 py-4 text-[22px] font-semibold leading-[1.5]"><Lines text={t.example??''}/></blockquote></div>)}</div>;
 if(slide.layout==='brands') return <div className="sdr-visual flex flex-col justify-center"><div className="grid grid-cols-4 gap-8">{tiles.map(t=><div key={t.title} className="flex flex-col items-center border-b-4 border-accent pb-7"><div className="flex h-[200px] w-full items-center justify-center bg-card p-8">{clientLogos[t.text]?<img src={clientLogos[t.text]} alt={t.title} className="max-h-[140px] max-w-full object-contain"/>:<span className="text-center text-[32px] font-bold text-primary">{t.title}</span>}</div><h3 className="mt-7 text-[26px] font-bold">{t.title}</h3></div>)}</div><div className="mt-10 flex items-center gap-5 text-[23px] text-muted-foreground"><Users className="text-accent" size={36}/>Jornada da Autonomia · Grupo Carrefour · cadeia de FLV</div></div>;
 if(slide.layout==='speech') return <div className="sdr-visual grid grid-cols-[220px_1fr] items-center gap-12"><div className="flex flex-col items-center gap-6"><span className="grid size-28 place-items-center rounded-full bg-accent text-accent-foreground"><Phone size={48}/></span><span className="text-[23px] font-bold">Ricardo · MyTS</span><div className="flex h-16 items-center gap-2 text-accent">{[24,42,60,32,48,64,40,28].map((h,i)=><span key={i} className="w-2 rounded-full bg-current" style={{height:h}}/>)}</div></div><blockquote className="border-l-8 border-accent pl-10 text-[32px] font-semibold leading-[1.65] text-foreground">“{tiles[0]?.text}”</blockquote></div>;
 if(slide.layout==='responses') return <div className="sdr-visual grid grid-cols-3 gap-7">{tiles.map(t=><div key={t.title} className="flex flex-col border-t-4 border-accent pt-6"><h3 className="min-h-[80px] text-[28px] font-bold leading-[1.35]">{t.title}</h3><div className="mt-5 flex-1 rounded-lg border border-border bg-card p-7"><MessageCircle size={32} className="mb-5 text-accent"/><p className="text-[23px] leading-[1.6]">“{t.text}”</p></div><span className="mt-5 text-[15px] font-bold text-accent">{t.tag}</span></div>)}</div>;
 if(slide.layout==='cadence') return <div className="sdr-visual grid grid-cols-3 grid-rows-2 gap-x-10 gap-y-7">{tiles.map((t,i)=><div key={t.title} className="flex gap-5 border-t-2 border-accent pt-5"><span className="grid size-14 shrink-0 place-items-center rounded-full bg-accent text-accent-foreground"><Icon name={t.icon} size={26}/></span><div><div className="flex items-center gap-3"><h3 className="text-[25px] font-bold">{t.title}</h3>{i<5&&<ArrowRight size={22} className="text-accent"/>}</div><p className="mt-4 text-[22px] leading-[1.55] text-muted-foreground"><Lines text={t.text}/></p></div></div>)}</div>;
 if(slide.layout==='practice') return <div className="sdr-visual grid grid-cols-[1fr_1.3fr_1fr_1.1fr] gap-6">{tiles.map(t=><div key={t.title} className="border-t-4 border-accent pt-5"><div className="flex items-center gap-3 text-accent"><Icon name={t.icon} size={28}/><h3 className="text-[25px] font-bold">{t.title}</h3></div><ul className="mt-5 space-y-3">{t.text.split('\n').map(line=><li key={line} className="flex gap-2 text-[18px] leading-[1.45] text-muted-foreground"><Check size={17} className="mt-1 shrink-0 text-success"/><span>{line}</span></li>)}</ul></div>)}</div>;
 if(slide.layout==='cover') return <div className="flex h-full items-center gap-16"><div className="w-[920px]"><span className="text-[22px] font-bold text-accent-glow">ONBOARDING SDR · MYTS BRASIL</span><h1 className="mt-7 text-[78px] font-bold leading-[1.12] text-primary-foreground">{slide.title}</h1><p className="mt-8 max-w-[800px] text-[28px] leading-[1.5] text-primary-foreground/70">{slide.subtitle}</p><div className="mt-14 grid grid-cols-4 gap-4">{tiles.map(t=><div key={t.title} className="border-t-2 border-accent pt-4"><span className="text-[24px] font-bold text-accent-glow">{t.title}</span><p className="mt-3 text-[18px] text-primary-foreground">{t.text}</p></div>)}</div></div><div className="relative flex h-[520px] flex-1 flex-col justify-center"><div className="absolute left-9 top-8 bottom-8 w-1 bg-accent/40"/>{['ENCONTRAR','ABORDAR','QUALIFICAR'].map((t,i)=><div key={t} className={`relative my-6 flex items-center gap-6 ${i===1?'ml-10':''}`}><div className="grid size-20 shrink-0 place-items-center rounded-full border-4 border-primary bg-accent text-accent-foreground"><Icon name={['search','phone','target'][i]} size={36}/></div><span className="text-[21px] font-bold text-primary-foreground">{t}</span></div>)}</div></div>;
 if(slide.layout==='guide') return <div className="sdr-visual"><div className="flex h-12 items-center gap-3 border-b border-border text-[17px] font-bold text-accent"><Columns3 size={21}/><span>RD STATION</span><ArrowRight size={18}/><span className="text-muted-foreground">ROTEIRO DA DEMONSTRAÇÃO</span></div>{tiles.map((t,i)=><div className="sdr-guide-row" key={t.title}><span className="grid size-14 place-items-center rounded-lg bg-accent/10 text-accent"><Icon name={t.icon} size={28}/></span><h3 className="text-[25px] font-bold">{t.title}</h3><p className="text-[22px] leading-[1.5] text-muted-foreground">{t.text}</p></div>)}</div>;
 if(slide.layout==='pyramid') return <div className="sdr-visual grid grid-cols-[.9fr_1.1fr] items-center gap-16"><div className="flex flex-col items-center gap-3">{tiles.map((t,i)=><div key={t.title} className={`${['w-[280px] bg-success text-success-foreground','w-[440px] bg-accent text-accent-foreground','w-[600px] bg-primary text-primary-foreground'][i]} flex h-[116px] items-center justify-center text-[24px] font-bold`}><span>0{i+1} · {['FOCO','DESENVOLVER','ORGANIZAR'][i]}</span></div>)}</div><div className="space-y-10">{tiles.map((t,i)=><div key={t.title} className="border-l-4 border-accent pl-7"><h3 className="text-[27px] font-bold">{t.title}</h3><p className="mt-3 text-[22px] leading-[1.5] text-muted-foreground">{t.text}</p></div>)}</div></div>;
 if(slide.layout==='script') return <div className="sdr-visual grid grid-cols-[.75fr_1.25fr] gap-14"><div className="flex flex-col justify-center border-l-8 border-accent pl-9"><Phone size={65} className="text-accent"/><p className="mt-8 text-[35px] font-bold leading-[1.4]">Quem você é.<br/>Por que importa.<br/>Qual o próximo passo.</p></div><div className="space-y-3">{tiles.map((t,i)=><div key={t.title} className={`flex items-center gap-6 rounded-lg px-6 py-4 ${i===4?'bg-primary text-primary-foreground':'bg-secondary'}`}><span className="text-[30px] font-bold text-accent">{i+1}</span><div><h3 className="text-[23px] font-bold">{t.title}</h3><p className={`mt-1 text-[18px] ${i===4?'text-primary-foreground/70':'text-muted-foreground'}`}>{t.text}</p></div>{i===4&&<span className="ml-auto text-[16px] font-bold text-accent-glow">SILÊNCIO</span>}</div>)}</div></div>;
 if(slide.layout==='bant') return <div className="sdr-visual grid grid-cols-4 gap-5">{tiles.map((t,i)=><div key={t.title} className="sdr-tile relative overflow-hidden border border-border bg-card p-7"><span className="text-[100px] font-bold leading-none text-accent/20">{t.tag}</span><div className="mt-9 text-accent"><Icon name={t.icon}/></div><h3 className="mt-5 text-[28px] font-bold">{t.title}</h3><p className="mt-5 text-[21px] leading-[1.5] text-muted-foreground">{t.text}</p></div>)}</div>;
 if(slide.layout==='planner') return <div className="sdr-visual overflow-hidden rounded-lg border border-border bg-card"><div className="flex h-14 items-center gap-4 border-b border-border bg-secondary px-6"><Columns3 size={24} className="text-accent"/><span className="text-[19px] font-bold">Comercial · Planner</span><span className="ml-auto text-[15px] text-muted-foreground">EXEMPLO ILUSTRATIVO</span></div><div className="grid h-[365px] grid-cols-4 gap-4 p-5">{tiles.map((t,i)=><div key={t.title} className="bg-secondary p-4"><div className="flex items-center justify-between border-b border-border pb-4"><h3 className="text-[20px] font-bold">{t.title}</h3><span className="grid size-7 place-items-center rounded-full bg-card text-[14px]">{t.text.split('\n').length}</span></div>{t.text.split('\n').map(text=><div key={text} className="sdr-tile mt-4 border border-border bg-card p-4"><div className={`mb-4 h-1 w-12 ${i===3?'bg-success':'bg-accent'}`}/><p className="text-[18px] leading-[1.4]">{text}</p><div className="mt-5 flex items-center gap-2 text-[14px] text-muted-foreground"><Check size={16}/>Tarefa comercial</div></div>)}</div>)}</div></div>;
 if(slide.layout==='closing') return <div className="flex h-full flex-col justify-center"><span className="text-[20px] font-bold text-accent-glow">RICARDO · MYTS BRASIL</span><h2 className="!mt-6 !max-w-[1250px] !text-[70px] text-primary-foreground">{slide.title}</h2><p className="mt-6 text-[32px] text-primary-foreground/70">{slide.subtitle}</p><div className="mt-12 flex gap-16">{tiles.map((t,i)=><div key={t.title} className="flex items-center gap-5"><span className="grid size-14 place-items-center rounded-full bg-accent text-accent-foreground"><Icon name={['message','file','repeat'][i]} size={26}/></span><div><h3 className="text-[25px] font-bold text-primary-foreground">{t.title}</h3><p className="text-[19px] text-primary-foreground/65">{t.text}</p></div></div>)}</div><p className="mt-14 text-[44px] font-bold text-accent-glow">{slide.takeaway}</p></div>;
 if(slide.layout==='timeline'||slide.layout==='flow'||slide.layout==='channels') return <div className="sdr-visual relative flex items-center"><div className="sdr-flow-line"/><div className="relative grid h-[380px] w-full gap-7" style={{gridTemplateColumns:`repeat(${tiles.length},minmax(0,1fr))`}}>{tiles.map((t,i)=><div key={t.title} className="flex flex-col"><div className={`grid size-24 place-items-center rounded-full border-8 ${dark?'border-primary':'border-background'} ${i===tiles.length-1?'bg-success text-success-foreground':'bg-accent text-accent-foreground'}`}><Icon name={t.icon} size={38}/></div><div className="mt-7 border-t border-accent/40 pt-6"><span className="text-[15px] font-bold text-accent">{String(i+1).padStart(2,'0')}</span><h3 className={`mt-3 text-[26px] font-bold ${ink}`}>{t.title}</h3><p className={`mt-4 text-[21px] leading-[1.5] ${muted}`}><Lines text={t.text}/></p></div></div>)}</div></div>;
 if(slide.layout==='discussion') return <div className="sdr-visual grid grid-cols-3 gap-8">{tiles.map((t,i)=><div key={t.title} className="flex flex-col border-t-4 border-accent pt-7"><span className="text-[74px] font-bold text-accent/20">0{i+1}</span><h3 className="mt-5 text-[28px] font-bold">{t.title}</h3><p className="mt-7 text-[29px] leading-[1.5]">{t.text}</p><div className="mt-auto flex gap-2">{[0,1,2].map(x=><span key={x} className="h-1 flex-1 bg-border"/>)}</div></div>)}</div>;
 if(slide.layout==='objections') return <div className="sdr-visual"><div className="mb-10 flex gap-5">{['“Não tenho interesse.”','“Manda por e-mail.”','“Estou ocupado.”'].map(x=><span key={x} className="flex-1 border-l-4 border-destructive bg-destructive/5 p-5 text-[24px] font-semibold">{x}</span>)}</div><div className="grid grid-cols-3 gap-8">{tiles.map((t,i)=><div key={t.title} className="border-t-2 border-accent pt-7"><div className="flex items-center gap-5"><span className="text-[35px] font-bold text-accent">0{i+1}</span><h3 className="text-[27px] font-bold">{t.title}</h3></div><p className="mt-6 text-[22px] text-muted-foreground">{t.text}</p></div>)}</div></div>;
 const isSplit=slide.layout==='split';const compact=tiles.length>=5;
 return <div className={`sdr-visual grid gap-5 ${isSplit?'grid-cols-2':''}`} style={!isSplit?{gridTemplateColumns:`repeat(${tiles.length},minmax(0,1fr))`}:undefined}>{tiles.map((t,i)=><div key={t.title} className={`sdr-tile ${compact?'p-6':'p-8'} ${dark?'border border-primary-foreground/15 bg-primary-foreground/5':i===1&&isSplit?'border-2 border-accent bg-accent/5':'border border-border bg-card'} ${slide.layout==='statement'?'flex flex-col justify-center':''}`}><TileBody tile={t} index={i} dark={dark}/>{slide.layout==='metrics'&&<div className="mt-8 flex items-center gap-3 border-t border-border pt-5"><span className="text-[40px] font-bold text-accent">—</span><span className={`text-[16px] ${muted}`}>Suporte para o acompanhamento</span></div>}</div>)}</div>;
}
