import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowRight, BellRing, Check, CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, Download, FileCheck2, FileText, FolderCheck, Mail, Maximize, MessageSquareText, Play, ShieldCheck, Users, Workflow } from 'lucide-react';
import QRCode from 'qrcode';
import { Button } from '@/components/ui/button';
import logo from '@/assets/myts-logo.svg';
import mark from '@/assets/myts-mark.svg?raw';
import ralston from '@/assets/ralston/ralston-logo.webp.asset.json';
import industry from '@/assets/material/industria-alimentos.jpg';
import { commercialClients } from '@/lib/commercial-proof';
import { commercialMetrics } from '@/lib/commercial-metrics';
import { ralstonPilot as p } from '@/lib/ralston-pilot';
import { ralstonStory as s } from '@/lib/ralston-story';
import '@/components/ralston/presentation.css';

const TOTAL = 12;
const logoUrl = new URL(ralston.url, 'https://id-preview--f991cff1-300a-49e4-bc63-d89deb2a73e4.lovable.app').href;
const markSvg = mark.replace(/fill="white"/g, 'fill="currentColor"');
function Brand({ both = false }: { both?: boolean }) { return <div className="flex items-center gap-6">{both && <><img src={logoUrl} alt="Ralston" className="h-24 w-24 object-contain"/><span className="text-muted-foreground text-3xl">×</span></>}<span className="rounded-lg bg-primary px-5 py-3"><img src={logo} alt="MyTS" className="h-10 w-auto"/></span></div>; }
function Frame({ n, label, dark = false, children }: { n: number; label: string; dark?: boolean; children: ReactNode }) {
  const ref = useRef<HTMLElement>(null); const [scale,setScale] = useState(1);
  const print = new URLSearchParams(location.search).has('print');
  useLayoutEffect(() => { const el=ref.current; if (!el || print) return; const update=()=>setScale(el.clientWidth/1600); update(); const observer=new ResizeObserver(update); observer.observe(el); return ()=>observer.disconnect(); }, [print]);
  return <section ref={ref} data-slide={n} className="ralston-frame"><div className={`ralston-canvas ${dark?'is-dark':''}`} style={{transform:`scale(${print?1:scale})`}}>
    {!dark&&<div className="ralston-mark" aria-hidden dangerouslySetInnerHTML={{__html:markSvg}}/>}
    <header className="relative flex items-center justify-between"><p className={`flex items-center gap-4 text-[19px] font-bold uppercase ${dark?'text-accent-glow':'text-accent'}`}><span>{String(n).padStart(2,'0')}</span><span className="h-px w-12 bg-current"/>{label}</p><span className={dark?'text-primary-foreground/70 text-[18px]':'text-muted-foreground text-[18px]'}>Ralston × MyTS</span></header>
    <div className="ralston-body">{children}</div><footer className="ralston-footer"><span>Do e-mail à MyTS · Piloto Ralston · {p.date}</span><span>{String(n).padStart(2,'0')} / {TOTAL}</span></footer>
  </div></section>;
}
const Title=({children}:{children:ReactNode})=><h2 className="ralston-title font-display">{children}</h2>;
const Bullet=({children}:{children:ReactNode})=><p className="flex items-start gap-4 text-[26px] leading-[1.45]"><CheckCircle2 className="mt-1 shrink-0 text-success" size={28}/>{children}</p>;
function Flow({items}:{items:{title:string;detail?:string}[]}) { return <div className="ralston-flow">{items.map((item,i)=><div key={item.title} className="flex min-w-0 flex-1 items-center gap-3"><div className="ralston-flow-step h-full"><span className="!mt-0 !text-accent font-bold">0{i+1}</span><strong className="mt-3">{item.title}</strong>{item.detail&&<span>{item.detail}</span>}</div>{i<items.length-1&&<ArrowRight size={22} className="shrink-0 text-accent"/>}</div>)}</div>; }
function Cover(){ return <Frame n={1} label="Uma experiência da Ralston" dark><div className="grid flex-1 grid-cols-[1.2fr_.8fr] items-center gap-14"><div><p className="text-[25px] text-accent-glow">{s.period}</p><h1 className="mt-7 font-display text-[98px] leading-[1.06] font-bold">Do e-mail<br/>à <span className="text-accent-glow">MyTS.</span></h1><p className="mt-8 text-[32px] leading-[1.4] max-w-[790px] text-primary-foreground/85">Como foi o nosso piloto<br/>de gestão de fornecedores.</p><p className="mt-10 text-[23px] text-primary-foreground/70">Gisele · Ralston</p></div><div className="relative"><img src={industry} alt="Produção na indústria de alimentos — imagem ilustrativa" className="h-[430px] w-full object-cover rounded-lg"/><div className="mt-6 flex justify-center rounded-lg bg-card p-4"><Brand both/></div></div></div></Frame>; }
function About(){return <Frame n={2} label="Sobre a MyTS"><Title>My Trusted Source.<br/><span className="text-accent">Uma base confiável para a indústria.</span></Title><div className="mt-9 grid flex-1 grid-cols-[1fr_510px] items-center gap-14"><div><p className="text-[29px] leading-[1.45]">A MyTS nasceu dentro da indústria de alimentos para reunir empresas, fornecedores e processos no mesmo lugar.</p><div className="mt-8 space-y-5"><Bullet>Documentos e histórico centralizados.</Bullet><Bullet>Etapas, responsáveis e evidências registrados.</Bullet><Bullet>Tecnologia e apoio de mais de 100 especialistas.</Bullet></div><div className="mt-8 grid grid-cols-3 gap-5 border-t border-border pt-7">{commercialMetrics.slice(0,3).map(m=><div key={m.label}><strong className="text-accent text-[37px] font-display font-bold">{m.value}</strong><p className="mt-2 text-[20px] text-muted-foreground">{m.label}</p></div>)}</div></div><div className="overflow-hidden rounded-lg bg-primary text-primary-foreground"><img src={industry} alt="Linha de produção de alimentos — imagem ilustrativa" className="h-[210px] w-full object-cover"/><div className="p-8"><Brand/><p className="mt-6 text-[25px] leading-[1.5]">Botucatu · Brasil<br/>Charlotte · Estados Unidos</p><p className="mt-5 text-[23px] text-accent-glow">Presença em mais de 20 países.</p></div></div></div></Frame>;}
function Clients(){return <Frame n={3} label="Clientes MyTS"><Title>Marcas que já confiam na MyTS.</Title><p className="ralston-subtitle">Algumas referências de quem utiliza a plataforma.</p><div className="my-auto grid grid-cols-3 gap-7">{commercialClients.slice(0,6).map(c=><div key={c.name} className="flex h-[190px] flex-col items-center justify-center gap-5 rounded-lg border border-border bg-card p-7"><img src={c.src} alt={c.name} className="h-[90px] w-[280px] object-contain"/><span className="text-[21px] text-muted-foreground">{c.name}</span></div>)}</div></Frame>;}
function Before(){return <Frame n={4} label="Como era"><Title>Um documento. <span className="text-accent">Sete passos.</span></Title><div className="mt-10"><Flow items={s.steps.map(title=>({title}))}/></div><div className="mt-12 grid grid-cols-2 gap-12 border-y border-border py-8"><div><p className="text-[26px] text-muted-foreground">80 fornecedores × 15 documentos</p><p className="mt-4 ralston-stat">1.200 <span className="text-[31px] font-normal text-foreground">documentos</span></p></div><div><p className="text-[26px] text-muted-foreground">1.200 documentos × 7 passos</p><p className="mt-4 ralston-stat">8.400 <span className="text-[31px] font-normal text-foreground">tarefas</span></p></div></div><div className="mt-7 ralston-callout">E cada documento tem seu próprio vencimento.</div><p className="mt-4 text-[19px] text-muted-foreground">Estimativa com base na média do piloto. Não é o volume efetivamente processado.</p></Frame>;}
function Decision(){return <Frame n={5} label="A decisão"><Title>Antes de mudar, <span className="text-accent">a gente testou.</span></Title><div className="my-auto grid grid-cols-4 gap-8">{[[String(s.days),'dias de teste','10/09 a 10/10/2026'],['R$ 0','de custo','Piloto sem custo'],[String(s.participants),'pessoas da Ralston','Participantes do teste'],[String(p.suppliers),'fornecedores','Diferentes tipos de fornecimento']].map(([n,l,d])=><div key={l} className="border-t-4 border-accent py-8"><strong className="ralston-stat">{n}</strong><h3 className="mt-6 text-[31px] font-bold">{l}</h3><p className="mt-4 text-[23px] text-muted-foreground leading-[1.5]">{d}</p></div>)}</div><div className="ralston-callout">Escolhemos fornecedores de tipos diferentes para ver se funcionava de verdade.</div></Frame>;}
function SupplierMock(){return <div className="ralston-window"><div className="ralston-window-head"><Users size={23} className="text-accent"/>MyTS · Acesso do fornecedor</div><div className="ralston-window-body"><p className="text-[20px] text-muted-foreground">Solicitação da Ralston · Parnaplast</p><h3 className="mt-3 text-[29px] font-bold">Meus documentos solicitados</h3>{[['Ficha técnica','Enviado'],['Declaração de conformidade','Enviado'],['Certificado atualizado','A enviar']].map(([name,status])=><div key={name} className="flex items-center justify-between gap-5 border-b border-border py-6 text-[23px]"><span className="flex items-center gap-3"><FileText size={24} className="text-accent"/>{name}</span><span className={status==='Enviado'?'text-success font-bold':'text-accent font-bold'}>{status}</span></div>)}<p className="mt-6 flex items-center gap-3 text-[22px] text-accent"><BellRing size={25}/>Avisos de pendência e vencimento</p><p className="mt-6 text-[17px] text-muted-foreground">Representação ilustrativa, não captura do piloto.</p></div></div>;}
function After(){return <Frame n={6} label="Como ficou"><Title>De sete passos <span className="text-accent">para dois.</span></Title><div className="mt-9 grid flex-1 grid-cols-[.95fr_1.05fr] gap-12 items-center"><div><p className="mb-6 text-[22px] text-muted-foreground">Antes: e-mail, cobrança, anexos e pastas.</p><Flow items={[{title:'O fornecedor envia',detail:'Acesso próprio para ver o que falta.'},{title:'A Qualidade aprova',detail:'Análise e histórico no mesmo lugar.'}]}/><div className="mt-8 space-y-5"><Bullet>Ele recebe avisos e anexa os documentos.</Bullet><Bullet>Nós validamos e acompanhamos.</Bullet><Bullet>O histórico fica com a Ralston.</Bullet></div></div><SupplierMock/></div></Frame>;}
function Results(){return <Frame n={7} label="O resultado"><Title>Quem participou <span className="text-accent">já trouxe resultado.</span></Title><div className="mt-10 flex items-center gap-10 border-y border-border py-7"><strong className="ralston-stat">44</strong><div><h3 className="text-[35px] font-bold">requisitos documentais aceitos</h3><p className="mt-3 text-[24px] text-muted-foreground">Recebidos e analisados pela plataforma.</p></div><FileCheck2 size={70} className="ml-auto text-success"/></div><div className="mt-10 grid grid-cols-3 gap-9">{[['Adel Coco','~8 dias','18 de 18 aceitos','100%'],['Parnaplast','12 de 12','Requisitos aceitos','100%'],['Grespan','11 de 12','1 ficha técnica recusada','92%']].map(([name,num,desc,percent])=><div key={name} className="rounded-lg border border-border bg-card p-7"><p className="text-[26px] font-bold">{name}</p><strong className="mt-5 block text-[56px] text-accent font-display">{num}</strong><p className="mt-3 text-[23px] text-muted-foreground">{desc}</p><div className="mt-6 h-3 bg-muted overflow-hidden rounded-full"><div className="h-full bg-success" style={{width:percent}}/></div></div>)}</div><p className="mt-7 text-[23px] text-muted-foreground">4 de 8 fornecedores responderam. Ainda há 83 requisitos pendentes; o trabalho continua.</p></Frame>;}
function Assessment(){return <Frame n={8} label="Autoavaliação"><Title>O formulário de Boas Práticas<br/><span className="text-accent">também mudou.</span></Title><div className="mt-8"><Flow items={[{title:'Ralston monta',detail:'Questionário e critérios.'},{title:'Fornecedor responde',detail:'Respostas e provas anexadas.'},{title:'Ralston analisa',detail:'Validação das evidências.'},{title:'Nota e não conformidades',detail:'Resultados após a análise.'}]}/></div><div className="mt-8 grid grid-cols-[1fr_.9fr] gap-12"><div className="ralston-callout"><strong className="block mb-3">Encontrou um problema?</strong>A não conformidade pode ser registrada no fluxo, ligada à avaliação e ao plano de ação.<p className="mt-4 text-[22px] text-accent font-bold">4 fornecedores no escopo · 1 resposta recebida<br/>Ainda sem avaliação aprovada.</p></div><div><h3 className="text-[25px] font-bold">Outros processos que funcionam assim</h3><div className="mt-5 grid grid-cols-2 gap-5">{['Homologação de fornecedor','Processo de compra','Checklist de recebimento','Plano de ação'].map(t=><p key={t} className="flex gap-3 text-[23px] leading-[1.4]"><Workflow className="shrink-0 text-accent" size={25}/>{t}</p>)}</div></div></div></Frame>;}
function Complete(){return <Frame n={9} label="O cenário completo"><Title>O que podemos reunir <span className="text-accent">na MyTS.</span></Title><p className="ralston-subtitle">Três módulos para organizar a rotina. Este é o cenário de expansão, não uma implantação já concluída.</p><div className="my-auto grid grid-cols-3 gap-10">{[{icon:Users,title:'Fornecedores',items:['Cadastro e requisitos','Cada um sabe o que enviar','Avisos antes de vencer']},{icon:Workflow,title:'Processos',items:['Avaliações e não conformidades','Resultados por fornecedor','Etapas e responsáveis visíveis']},{icon:FolderCheck,title:'Documentos internos',items:['Versão vigente','Aviso na hora de revisar','Histórico de cada mudança']}].map(({icon:Icon,title,items})=><div key={title} className="border-t-4 border-accent pt-8"><Icon size={48} className="text-accent"/><h3 className="mt-6 text-[36px] font-bold">{title}</h3><div className="mt-7 space-y-6">{items.map(t=><Bullet key={t}>{t}</Bullet>)}</div></div>)}</div></Frame>;}
function Qr({url}:{url:string}){const [src,setSrc]=useState('');useEffect(()=>{let active=true;QRCode.toDataURL(url,{width:180,margin:1,errorCorrectionLevel:'M'}).then(value=>{if(active)setSrc(value);});return()=>{active=false;};},[url]);return src?<img src={src} alt="Código QR para assistir ao vídeo" className="h-[140px] w-[140px]"/>:<div className="h-[140px] w-[140px]"/>;}
function Videos(){return <Frame n={10} label="Veja funcionando"><Title>Veja como funciona <span className="text-accent">na prática.</span></Title><div className="my-auto grid grid-cols-3 gap-8">{s.videos.map((v,i)=><a href={v.url} key={v.url} target="_blank" rel="noopener noreferrer" className="overflow-hidden rounded-lg border border-border bg-card focus-visible:outline-accent"><div className="ralston-video-visual"><div className="flex items-center gap-3 text-[18px] text-muted-foreground"><span className="h-3 w-3 rounded-full bg-accent"/>MyTS · {v.title}</div><div className="mt-6 flex items-center gap-7"><span className="grid size-20 place-items-center rounded-full bg-accent text-accent-foreground"><Play size={35}/></span><div className="flex-1 space-y-3">{[0,1,2].map(n=><div key={n} className="flex items-center gap-3 border-b border-border pb-3"><Check size={20} className="text-success"/><span className={`h-2 rounded-full bg-accent/20 ${n===1?'w-24':'w-36'}`}/></div>)}</div></div></div><div className="p-7"><p className="text-accent text-[20px] font-bold">VÍDEO 0{i+1}</p><h3 className="mt-3 text-[30px] leading-tight font-bold">{v.title}</h3><div className="mt-6 flex items-center justify-between gap-5"><span className="text-[22px] font-semibold text-accent">Assistir <ArrowRight className="mt-3"/></span><Qr url={v.url}/></div></div></a>)}</div><p className="text-[23px] text-muted-foreground">Clique no vídeo ou use o código QR. Os vídeos também ficam disponíveis depois da apresentação.</p></Frame>;}
function Verification(){return <Frame n={11} label="Pronta para verificações"><Title>Chegou visita?<br/><span className="text-accent">O documento está aqui.</span></Title><div className="mt-10 grid flex-1 grid-cols-[.9fr_1.1fr] gap-14 items-center"><div className="space-y-7">{['Vigilância Sanitária','Auditoria de cliente','Visita técnica'].map(t=><p key={t} className="flex items-center gap-5 text-[32px] font-semibold"><ShieldCheck size={40} className="text-accent"/>{t}</p>)}<p className="mt-8 text-[27px] leading-[1.5] text-muted-foreground">Localizar, conferir a validade e mostrar a evidência no mesmo lugar.</p></div><div className="ralston-window"><div className="ralston-window-head"><FileText className="text-accent"/>Documentos e evidências</div><div className="ralston-window-body"><p className="rounded-lg bg-secondary p-4 text-[24px] text-muted-foreground">Buscar documento, produto ou fornecedor</p>{[['Ficha técnica','Versão vigente'],['Certificado','Validade registrada'],['Avaliação','Evidências anexadas']].map(([t,d])=><div key={t} className="flex items-center justify-between border-b border-border py-7 text-[25px]"><strong>{t}</strong><span className="text-success text-[22px]">{d}</span></div>)}<p className="mt-5 text-[18px] text-muted-foreground">Representação ilustrativa. A validade depende da atualização e análise dos documentos.</p></div></div></div></Frame>;}
function Next(){return <Frame n={12} label="Próximo passo" dark><Title>O piloto mostrou o caminho.<br/><span className="text-accent-glow">Agora, decidir como ampliar.</span></Title><div className="mt-10 grid flex-1 grid-cols-[1.1fr_.9fr] gap-14 items-center"><div className="space-y-8">{['Fornecedores já enviaram pelo próprio acesso.','Documentos e histórico ficaram centralizados.','A primeira autoavaliação já chegou.'].map(t=><p key={t} className="flex items-start gap-5 text-[31px] leading-[1.4]"><CheckCircle2 size={34} className="mt-1 shrink-0 text-accent-glow"/>{t}</p>)}<p className="mt-9 border-t border-primary-foreground/20 pt-7 text-[28px] text-primary-foreground/80">Concluir pendências, ouvir as áreas<br/>e alinhar a continuidade.</p></div><div className="border-l border-primary-foreground/20 pl-10"><MessageSquareText size={48} className="text-accent-glow"/><h3 className="mt-6 text-[33px] font-bold">O que as áreas acharam?</h3><p className="mt-5 text-[26px] text-primary-foreground/75 leading-[1.5]">Retorno a registrar com a equipe da Ralston.</p><p className="mt-12 text-[31px] leading-[1.4] text-accent-glow font-semibold">Em cada verificação,<br/>evidências fáceis de encontrar.</p></div></div></Frame>;}
const slides=[Cover,About,Clients,Before,Decision,After,Results,Assessment,Complete,Videos,Verification,Next];
export default function ApresentacaoImplantacaoRalston(){
 const print=new URLSearchParams(location.search).has('print');
 const initial=Number(new URLSearchParams(location.search).get('slide')||1);
 const [current,setCurrent]=useState(Number.isFinite(initial)?Math.max(1,Math.min(TOTAL,initial)):1);
 const [notes,setNotes]=useState(false); const root=useRef<HTMLElement>(null);
 const go=(delta:number)=>setCurrent(n=>Math.max(1,Math.min(TOTAL,n+delta)));
 useEffect(()=>{if(print)return; const handler=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();setCurrent(n=>Math.min(TOTAL,n+1));}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();setCurrent(n=>Math.max(1,n-1));}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[print]);
 useEffect(()=>{if(print)return;const url=new URL(location.href);url.searchParams.set('slide',String(current));history.replaceState(null,'',url);},[current,print]);
 const Active=slides[current-1]??Cover;
 return <main ref={root} className={`ralston-deck ${print?'ralston-print':''}`}><Helmet><title>Do e-mail à MyTS — Piloto Ralston</title><meta name="description" content="A experiência da Ralston no piloto de gestão de fornecedores: rotina, resultados e próximos passos, de agosto a outubro de 2026."/><meta property="og:title" content="Do e-mail à MyTS — Piloto Ralston"/><meta property="og:description" content="A experiência da Ralston com documentos, fornecedores e processos na MyTS."/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary_large_image"/></Helmet>
 {!print&&<div className="ralston-toolbar no-print"><span className="ralston-toolbar-label text-primary-foreground/80 font-semibold">Do e-mail à MyTS · Ralston</span><div className="flex gap-2"><Button variant="secondary" aria-pressed={notes} onClick={()=>setNotes(n=>!n)}><MessageSquareText/>Fala da Gisele</Button><Button variant="secondary" size="icon" title="Tela cheia" aria-label="Tela cheia" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void root.current?.requestFullscreen();}}><Maximize/></Button><Button onClick={()=>window.open(`${location.pathname}?print`,'_blank','noopener')} className="bg-accent text-accent-foreground"><Download/>PDF</Button></div></div>}
 {print?slides.map((S,i)=><S key={i}/>):<Active/>}
 {!print&&notes&&<aside className="ralston-notes no-print"><strong className="text-accent">Fala da Gisele · {current} / {TOTAL}</strong><p className="mt-3">{s.notes[current-1]}</p></aside>}
 {!print&&<nav className="ralston-controls no-print" aria-label="Navegação da apresentação"><Button variant="ghost" size="icon" disabled={current===1} aria-label="Slide anterior" onClick={()=>go(-1)} className="text-primary-foreground"><ChevronLeft/></Button><span className="min-w-20 text-center text-lg font-semibold">{current} / {TOTAL}</span><Button variant="ghost" size="icon" disabled={current===TOTAL} aria-label="Próximo slide" onClick={()=>go(1)} className="text-primary-foreground"><ChevronRight/></Button></nav>}
 {print&&<div className="no-print fixed right-5 top-5"><Button onClick={()=>window.print()}><Download/>Salvar PDF</Button></div>}
 </main>;
}
