import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { ChevronLeft, ChevronRight, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import mytsLogo from '@/assets/myts-logo.svg';
import OnboardingVisual from '@/components/sdr/OnboardingVisual';
import { blocks, onboardingSlides, type DeckSlide } from '@/components/sdr/onboarding-content';
import '@/components/sdr/onboarding.css';
const TOTAL=onboardingSlides.length;
function Slide({slide,n,print}:{slide:DeckSlide;n:number;print:boolean}) {
 const ref=useRef<HTMLElement>(null);const [scale,setScale]=useState(print?1:0);const [visible,setVisible]=useState(print);
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;const update=()=>setScale(print?1:el.clientWidth/1600);update();const resize=new ResizeObserver(update);resize.observe(el);const observer=new IntersectionObserver(([entry])=>{if(entry?.isIntersecting)setVisible(true);},{threshold:.25});observer.observe(el);return()=>{resize.disconnect();observer.disconnect();};},[print]);
 const dark=!!slide.dark;const special=slide.layout==='cover'||slide.layout==='closing';
 return <section ref={ref} data-slide={n} data-block={slide.block} aria-label={`Lâmina ${n}: ${slide.title}`} className={`sdr-slide ${dark?'bg-primary':'bg-background'}`}><div className={`sdr-canvas ${dark?'bg-primary':'bg-background'}`} style={{transform:`scale(${scale})`,visibility:scale?'visible':'hidden'}}><div className="sdr-content"><header className={`flex h-9 shrink-0 items-center justify-between text-[15px] font-bold ${dark?'text-accent-glow':'text-accent'}`}><div className="flex items-center gap-5"><span className="border-r border-current pr-5">BLOCO {String(slide.block).padStart(2,'0')}</span><span>{slide.label}</span></div><div className="flex gap-2">{blocks.map((b,i)=><span key={b} className={`h-1 w-12 ${i+1===slide.block?'bg-accent':'bg-accent/20'}`}/>)}</div></header><div className={`${special?'flex-1':'shrink-0'} ${visible?'sdr-reveal':''}`}>
 {!special&&<><h2 className={dark?'text-primary-foreground':'text-foreground'}>{slide.title}</h2>{slide.subtitle&&<p className={`sdr-subtitle ${dark?'text-primary-foreground/70':'text-muted-foreground'}`}>{slide.subtitle}</p>}</>}
 <OnboardingVisual slide={slide}/>
 </div>{!special&&slide.takeaway&&<div className={`mt-6 border-l-4 border-accent pl-5 text-[23px] font-bold leading-[1.35] ${dark?'text-accent-glow':'text-accent'}`}>{slide.takeaway}</div>}
 <footer className={`mt-auto flex min-h-[63px] shrink-0 items-end justify-between gap-7 border-t pt-4 ${dark?'border-primary-foreground/15':'border-border'}`}><div className="rounded bg-primary px-3 py-2"><img src={mytsLogo} alt="MyTS" className="h-6 w-auto"/></div>{slide.note&&<p className={`sdr-note max-w-[1100px] ${dark?'text-primary-foreground/60':'text-muted-foreground'}`}>{slide.note}</p>}<span className={`shrink-0 text-[16px] font-bold ${dark?'text-primary-foreground/60':'text-muted-foreground'}`}>{String(n).padStart(2,'0')} / {TOTAL}</span></footer></div></div></section>;
}
export default function TreinamentoSdr(){
 const print=new URLSearchParams(window.location.search).has('print');const [current,setCurrent]=useState(1);
 const go=(n:number)=>document.querySelector<HTMLElement>(`[data-slide="${Math.min(TOTAL,Math.max(1,n))}"]`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});
 useEffect(()=>{if(print)return;const sections=Array.from(document.querySelectorAll<HTMLElement>('[data-slide]'));const onScroll=()=>{let best:HTMLElement|undefined;let distance=Infinity;for(const section of sections){const rect=section.getBoundingClientRect();const d=Math.abs(rect.top+rect.height/2-window.innerHeight/2);if(d<distance){distance=d;best=section;}}if(best)setCurrent(Number(best.dataset.slide));};const onKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(current+1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(current-1);}};onScroll();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('keydown',onKey);};},[print,current]);
 return <main className={`sdr-deck flex min-h-screen flex-col items-center overflow-x-hidden bg-primary ${print?'gap-0':'gap-8 py-12'}`}><Helmet><title>Onboarding SDR · Ricardo — MyTS Brasil</title><meta name="description" content="Treinamento SDR MyTS: mentalidade, jornada comercial, guia de demonstração do RD Station e rotinas de evolução."/><meta property="og:title" content="Onboarding SDR · MyTS Brasil"/><meta property="og:description" content="Da primeira conversa à operação comercial: treinamento do Ricardo e demonstração do CRM."/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary_large_image"/><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Sora:wght@400;500;600;700;800&display=swap"/></Helmet>
 {!print&&<><Button onClick={()=>window.print()} className="sdr-controls fixed right-5 top-4 z-50 bg-accent text-accent-foreground"><Download size={18}/>Baixar PDF</Button><nav aria-label="Navegação do treinamento" className="sdr-controls fixed bottom-4 left-1/2 z-50 flex max-w-[96vw] -translate-x-1/2 items-center gap-3 rounded-lg border border-primary-foreground/20 bg-primary p-2 shadow-elegant"><Button variant="ghost" size="icon" aria-label="Slide anterior" disabled={current===1} onClick={()=>go(current-1)} className="text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><ChevronLeft/></Button><span className="min-w-[65px] text-center text-[14px] font-bold text-primary-foreground">{current} / {TOTAL}</span><Button variant="ghost" size="icon" aria-label="Próximo slide" disabled={current===TOTAL} onClick={()=>go(current+1)} className="text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><ChevronRight/></Button><div className="hidden border-l border-primary-foreground/20 pl-3 sm:block"><select aria-label="Ir para bloco" value={onboardingSlides[current-1]?.block??1} onChange={e=>{const index=onboardingSlides.findIndex(s=>s.block===Number(e.target.value));go(index+1);}} className="max-w-[280px] bg-primary p-2 text-[13px] text-primary-foreground">{blocks.map((b,i)=><option key={b} value={i+1}>{i+1}. {b}</option>)}</select></div></nav></>}
 {onboardingSlides.map((slide,i)=><Slide key={i} slide={slide} n={i+1} print={print}/>)}</main>;
}
